### ISSUE TITLE
Unavailability of parts

### ISSUE THREAD

**Issue by 0ddjob** [schlae/graphics-gremlin#13]
A few parts are currently unavailable from several suppliers with long lead-times from the manufacturer - is there a possibility of alternatives?

U1: iCE40HX4K-TQ144
U10: APX803S00-29SA-7

**Comment by schlae** [comment]
U10: A large number of alternatives are available, this is a clone of a MAX803. be sure to check voltage levels and pinouts before substituting.
U1: No alternatives. We just have to wait until it gets back into stock :(

**Comment by midicdj1000** [comment]
HI, Any alternatives for the RCA socket ?
