### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by vazhnov** [schlae/graphics-gremlin#20]
Hello!

Thank you for a great project, published under opensource license!

Could you please add a file `LICENSE` or `COPYING` with a license text, so the forks (like https://github.com/yeokm1/graphics-gremlin-hdmi) wouldn't loose it by a mistake?

It is easy to add the file with GitHub, it has the license template.

If you want, I can help you.

**Comment by schlae** [comment]
Fixed, see 709f624
