### ISSUE TITLE
Centroid file

### ISSUE THREAD

**Issue by cstruter** [schlae/graphics-gremlin#23]
I just ordered this on pcbway, but you didnt supply a centroid file.
[https://www.pcbway.com/project/shareproject/The_Graphics_Gremlin_a_Retro_ISA_Video_Card_8294bddc.html](url)

**Comment by cstruter** [comment]
[PickAndPlace_isavideo_2024-10-24.xlsx](https://github.com/user-attachments/files/17511319/PickAndPlace_isavideo_2024-10-24.xlsx)
Is this good enough?

**Comment by schlae** [comment]
Fixed, the CSV coordinate file is now in the fab package, see 9954a99.
