### ISSUE TITLE
Question about the specified board size

### ISSUE THREAD

**Issue by ecm-pushbx** [schlae/graphics-gremlin#4]
I don't really go here but I found the following part of the readme file curious:

> The circuit board is a 2-layer board, 4.19 x 4.2 inches (106 x 95mm).

1. The shorter and longer sides seem to be swapped between the inches and millimetres specifications.
2. I don't see how the values are accurate matches. Perhaps the "4.2 inches" should be "4.02 inches"? That still wouldn't match exactly though.

**Comment by schlae** [comment]
The height should be 3.74in, or 95mm. I've corrected it in the board file and the readme.
