### ISSUE TITLE
Gremlin over pci(e), serial, or other bus?

### ISSUE THREAD

**Issue by AsureDawn** [schlae/graphics-gremlin#6]
Is it possible to use gremlin over another bus, or are you aware of another project which allows this?

Sorry, I realize this is only tangentially related to the project, but I really cannot find any other way to get graphics working on DOS in a modern machine (other than emulating/virtualizing the entire machine).

**Comment by schlae** [comment]
In theory, yes, what you need is [a USB to ISA bridge](http://arstech.com/install/ecom-prodshow/usb2isar.html) however there is a bunch of software you'd need to write to get the DOS program to use it. Likely it's only possible through emulation.
