### ISSUE TITLE
Can I replace with ICE40HX1K-TQ144?

### ISSUE THREAD

**Issue by yeokm1** [schlae/graphics-gremlin#7]
Hi

I'm intending to assemble your board however I realised ICE40HX4K-TQ144 is out of stock everywhere.

Will a ICE40HX1K-TQ144 work instead?

**Comment by schlae** [comment]
No, the 1K has fewer I/O pins, and the Gremlin uses nearly every available I/O on the 4K. You'll just have to wait until they get back in stock.
