### ISSUE TITLE
ICE40HX chips might have 5V tolerant I/O

### ISSUE THREAD

**Issue by kiwidrew** [schlae/graphics-gremlin#8]
If you're willing to live a little bit dangerously the second 74ALVC164245 (U5) may not be necessary because [it appears that the HX4K has 5V tolerant I/O pins](https://www.eevblog.com/forum/fpga/ice40-hx-a-5v-tolerant-fpga/) despite what the datasheet claims.

**Comment by schlae** [comment]
I hesitate to design it this way--the FPGA won't last as long due to possible electromigration effects.
